"""
AgentNexus SDK Action Layer

Implements the four collaboration action types:
- task_propose: Publish/delegate a task
- task_claim: Claim/respond to a task
- resource_sync: Share key-value data
- state_notify: Report progress/status

Based on ADR-007: Action Layer Protocol Design
"""
from dataclasses import dataclass, field, asdict
from typing import Optional, Any, Dict
from enum import Enum
import json


PROTOCOL_NEXUS_V1 = "nexus_v1"


class ActionType(str, Enum):
    """Action Layer message types."""
    TASK_PROPOSE = "task_propose"
    TASK_CLAIM = "task_claim"
    RESOURCE_SYNC = "resource_sync"
    STATE_NOTIFY = "state_notify"


class TaskStatus(str, Enum):
    """Task status values for state_notify."""
    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    FAILED = "failed"
    BLOCKED = "blocked"


@dataclass
class ActionMessage:
    """Base class for Action Layer messages."""
    from_did: str
    message_type: str
    content: Dict[str, Any]


@dataclass
class TaskPropose:
    """
    Publish or delegate a task.

    Content structure:
    - task_id: Unique identifier (generated by sender)
    - title: Task title (required)
    - description: Detailed description (optional)
    - deadline: ISO date string (optional)
    - required_caps: Required capabilities (optional)
    - priority: Priority level (optional)
    """
    task_id: str
    title: str
    description: Optional[str] = None
    deadline: Optional[str] = None
    required_caps: Optional[list[str]] = None
    priority: Optional[str] = None

    def to_content(self) -> dict:
        """Convert to content dict for send()."""
        content = {"task_id": self.task_id, "title": self.title}
        if self.description:
            content["description"] = self.description
        if self.deadline:
            content["deadline"] = self.deadline
        if self.required_caps:
            content["required_caps"] = self.required_caps
        if self.priority:
            content["priority"] = self.priority
        return content

    @classmethod
    def from_content(cls, content: dict) -> "TaskPropose":
        """Parse from content dict."""
        return cls(
            task_id=content["task_id"],
            title=content["title"],
            description=content.get("description"),
            deadline=content.get("deadline"),
            required_caps=content.get("required_caps"),
            priority=content.get("priority"),
        )


@dataclass
class TaskClaim:
    """
    Claim or respond to a task.

    Content structure:
    - task_id: The task being claimed (required)
    - eta: Estimated time to complete (optional)
    - message: Optional message to the task proposer
    """
    task_id: str
    eta: Optional[str] = None
    message: Optional[str] = None

    def to_content(self) -> dict:
        content = {"task_id": self.task_id}
        if self.eta:
            content["eta"] = self.eta
        if self.message:
            content["message"] = self.message
        return content

    @classmethod
    def from_content(cls, content: dict) -> "TaskClaim":
        return cls(
            task_id=content["task_id"],
            eta=content.get("eta"),
            message=content.get("message"),
        )


@dataclass
class ResourceSync:
    """
    Share key-value data.

    Content structure:
    - key: Resource identifier (required)
    - value: Resource value (required)
    - version: Version string (optional)
    """
    key: str
    value: Any
    version: Optional[str] = None

    def to_content(self) -> dict:
        content = {"key": self.key, "value": self.value}
        if self.version:
            content["version"] = self.version
        return content

    @classmethod
    def from_content(cls, content: dict) -> "ResourceSync":
        return cls(
            key=content["key"],
            value=content["value"],
            version=content.get("version"),
        )


@dataclass
class StateNotify:
    """
    Report progress or status.

    Content structure:
    - task_id: Associated task (optional)
    - status: Current status (required: pending/in_progress/completed/failed/blocked)
    - progress: Progress percentage 0.0-1.0 (optional)
    - error: Error message if status is 'failed' (optional)
    """
    status: str
    task_id: Optional[str] = None
    progress: Optional[float] = None
    error: Optional[str] = None

    def to_content(self) -> dict:
        content = {"status": self.status}
        if self.task_id:
            content["task_id"] = self.task_id
        if self.progress is not None:
            content["progress"] = self.progress
        if self.error:
            content["error"] = self.error
        return content

    @classmethod
    def from_content(cls, content: dict) -> "StateNotify":
        return cls(
            status=content["status"],
            task_id=content.get("task_id"),
            progress=content.get("progress"),
            error=content.get("error"),
        )

    def is_terminal(self) -> bool:
        """Check if this is a terminal state."""
        return self.status in (TaskStatus.COMPLETED, TaskStatus.FAILED)


# ── Task State Machine ────────────────────────────────────────────

class TaskStatus(str, Enum):
    """Task status values for state_notify."""
    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    FAILED = "failed"
    BLOCKED = "blocked"
    EXPIRED = "expired"  # 超时过期状态


class TaskStateMachine:
    """
    Light-weight task state machine for SDK-side tracking.

    Valid transitions:
    - pending -> in_progress (task_claim)
    - pending -> expired (timeout, SDK-local)
    - in_progress -> completed (state_notify)
    - in_progress -> failed (state_notify)
    - in_progress -> blocked (state_notify)
    - blocked -> in_progress (state_notify, recovery)
    """

    VALID_TRANSITIONS = {
        TaskStatus.PENDING: [TaskStatus.IN_PROGRESS, TaskStatus.EXPIRED],
        TaskStatus.IN_PROGRESS: [TaskStatus.COMPLETED, TaskStatus.FAILED, TaskStatus.BLOCKED],
        TaskStatus.BLOCKED: [TaskStatus.IN_PROGRESS],
        TaskStatus.COMPLETED: [],  # Terminal
        TaskStatus.FAILED: [],     # Terminal
        TaskStatus.EXPIRED: [],    # Terminal
    }

    def __init__(self, initial_status: str = TaskStatus.PENDING):
        self._status = initial_status
        self._history: list[tuple[str, float]] = []

    @property
    def status(self) -> str:
        return self._status

    def transition(self, new_status: str) -> bool:
        """
        Attempt to transition to a new status.

        Returns:
            True if transition is valid, False otherwise
        """
        valid_next = self.VALID_TRANSITIONS.get(self._status, [])
        if new_status in valid_next:
            import time
            self._history.append((self._status, time.time()))
            self._status = new_status
            return True
        return False

    def is_terminal(self) -> bool:
        """Check if current state is terminal."""
        return self._status in (TaskStatus.COMPLETED, TaskStatus.FAILED, TaskStatus.EXPIRED)
