"""
AgentNexus SDK Discussion Protocol

Implements the four discussion action types:
- discussion_start: Start a new discussion
- discussion_reply: Reply with optional quote/mention
- discussion_vote: Cast a vote
- discussion_conclude: Close discussion with conclusion

Based on ADR-011: Discussion Protocol Design
"""
from dataclasses import dataclass
from typing import Optional, List
from enum import Enum

from .constants import (
    PROTOCOL_NEXUS_V1 as PROTOCOL_NEXUS_V1,
    PROTOCOL_NEXUS_V1_INTERNAL as PROTOCOL_NEXUS_V1_INTERNAL,
)


class DiscussionMessageType(str, Enum):
    """Discussion Protocol message types."""
    START = "discussion_start"
    REPLY = "discussion_reply"
    VOTE = "discussion_vote"
    CONCLUDE = "discussion_conclude"
    # Internal state message (not routed)
    VOTE_STATE = "discussion_vote_state"


class ConsensusMode(str, Enum):
    """Consensus modes for voting."""
    MAJORITY = "majority"        # Simple majority
    UNANIMOUS = "unanimous"      # All must agree
    LEADER_DECIDES = "leader_decides"  # Leader makes final decision


class TimeoutAction(str, Enum):
    """Actions to take on timeout."""
    AUTO_APPROVE = "auto_approve"
    AUTO_REJECT = "auto_reject"
    ESCALATE = "escalate"


class ConclusionType(str, Enum):
    """Types of discussion conclusion."""
    CONSENSUS = "consensus"        # Agreement reached
    NO_CONSENSUS = "no_consensus"  # Disagreement recorded
    ESCALATED = "escalated"        # Escalated for decision


# ── Data Models ────────────────────────────────────────────────────────

@dataclass
class Consensus:
    """Consensus rules for a discussion."""
    mode: str  # ConsensusMode value
    leader_did: Optional[str] = None  # Required if mode == leader_decides
    timeout_seconds: Optional[int] = None
    timeout_action: Optional[str] = None  # TimeoutAction value

    def to_dict(self) -> dict:
        result = {"mode": self.mode}
        if self.leader_did:
            result["leader_did"] = self.leader_did
        if self.timeout_seconds is not None:
            result["timeout_seconds"] = self.timeout_seconds
        if self.timeout_action:
            result["timeout_action"] = self.timeout_action
        return result

    @classmethod
    def from_dict(cls, data: dict) -> "Consensus":
        return cls(
            mode=data["mode"],
            leader_did=data.get("leader_did"),
            timeout_seconds=data.get("timeout_seconds"),
            timeout_action=data.get("timeout_action"),
        )


@dataclass
class ActionItem:
    """An action item from a discussion conclusion."""
    type: str  # "update_document", "create_task", etc.
    description: str
    ref: Optional[str] = None  # Logical identifier (e.g., "adr-007")

    def to_dict(self) -> dict:
        result = {"type": self.type, "description": self.description}
        if self.ref:
            result["ref"] = self.ref
        return result

    @classmethod
    def from_dict(cls, data: dict) -> "ActionItem":
        return cls(
            type=data["type"],
            description=data["description"],
            ref=data.get("ref"),
        )


@dataclass
class DiscussionStart:
    """
    Start a new discussion.

    Content structure:
    - topic_id: Unique identifier (generated by sender)
    - title: Discussion title (required)
    - participants: List of participant DIDs (required)
    - context: Optional context/background
    - consensus: Optional consensus rules (null = pure discussion)
    - related_task_id: Optional related task
    - seq: Sequence number (starts at 1)
    """
    topic_id: str
    title: str
    participants: List[str]
    context: Optional[str] = None
    consensus: Optional[Consensus] = None
    related_task_id: Optional[str] = None
    seq: int = 1

    def to_content(self) -> dict:
        content = {
            "topic_id": self.topic_id,
            "title": self.title,
            "participants": self.participants,
            "seq": self.seq,
        }
        if self.context:
            content["context"] = self.context
        if self.consensus:
            content["consensus"] = self.consensus.to_dict()
        if self.related_task_id:
            content["related_task_id"] = self.related_task_id
        return content

    @classmethod
    def from_content(cls, content: dict) -> "DiscussionStart":
        consensus = None
        if "consensus" in content and content["consensus"]:
            consensus = Consensus.from_dict(content["consensus"])
        return cls(
            topic_id=content["topic_id"],
            title=content["title"],
            participants=content["participants"],
            context=content.get("context"),
            consensus=consensus,
            related_task_id=content.get("related_task_id"),
            seq=content.get("seq", 1),
        )


@dataclass
class DiscussionReply:
    """
    Reply to a discussion.

    Content structure:
    - topic_id: The discussion being replied to
    - content: Reply content (required)
    - reply_to: Optional message ID being replied to
    - mentions: Optional list of mentioned DIDs
    - request_escalate: Request escalation if true
    - seq: Sequence number
    """
    topic_id: str
    content: str
    reply_to: Optional[int] = None
    mentions: Optional[List[str]] = None
    request_escalate: bool = False
    seq: int = 1

    def to_content(self) -> dict:
        result = {
            "topic_id": self.topic_id,
            "content": self.content,
            "seq": self.seq,
        }
        if self.reply_to is not None:
            result["reply_to"] = self.reply_to
        if self.mentions:
            result["mentions"] = self.mentions
        if self.request_escalate:
            result["request_escalate"] = True
        return result

    @classmethod
    def from_content(cls, content: dict) -> "DiscussionReply":
        return cls(
            topic_id=content["topic_id"],
            content=content["content"],
            reply_to=content.get("reply_to"),
            mentions=content.get("mentions"),
            request_escalate=content.get("request_escalate", False),
            seq=content.get("seq", 1),
        )


@dataclass
class DiscussionVote:
    """
    Cast a vote in a discussion.

    Content structure:
    - topic_id: The discussion being voted on
    - vote: "approve", "reject", or "abstain"
    - reason: Optional reason for the vote
    - seq: Sequence number
    """
    topic_id: str
    vote: str  # "approve", "reject", "abstain"
    reason: Optional[str] = None
    seq: int = 1

    def to_content(self) -> dict:
        result = {
            "topic_id": self.topic_id,
            "vote": self.vote,
            "seq": self.seq,
        }
        if self.reason:
            result["reason"] = self.reason
        return result

    @classmethod
    def from_content(cls, content: dict) -> "DiscussionVote":
        return cls(
            topic_id=content["topic_id"],
            vote=content["vote"],
            reason=content.get("reason"),
            seq=content.get("seq", 1),
        )


@dataclass
class DiscussionConclude:
    """
    Conclude a discussion.

    Content structure:
    - topic_id: The discussion being concluded
    - conclusion: Conclusion text (required)
    - conclusion_type: Type of conclusion (optional, default: "consensus")
    - action_items: Optional list of follow-up actions
    - seq: Sequence number
    """
    topic_id: str
    conclusion: str
    conclusion_type: str = ConclusionType.CONSENSUS
    action_items: Optional[List[ActionItem]] = None
    seq: int = 1

    def to_content(self) -> dict:
        result = {
            "topic_id": self.topic_id,
            "conclusion": self.conclusion,
            "conclusion_type": self.conclusion_type,
            "seq": self.seq,
        }
        if self.action_items:
            result["action_items"] = [ai.to_dict() for ai in self.action_items]
        return result

    @classmethod
    def from_content(cls, content: dict) -> "DiscussionConclude":
        action_items = None
        if "action_items" in content:
            action_items = [ActionItem.from_dict(ai) for ai in content["action_items"]]
        return cls(
            topic_id=content["topic_id"],
            conclusion=content["conclusion"],
            conclusion_type=content.get("conclusion_type", ConclusionType.CONSENSUS),
            action_items=action_items,
            seq=content.get("seq", 1),
        )


__all__ = [name for name in globals() if not name.startswith("__")]
