"""Run an L0-ready Objective Loop demo with three real local Worker DIDs.

This script is intentionally a smoke/demo harness, not a test fixture. It
registers:
- a deterministic script/pytest worker for clarify, design and test
- a Claude worker for implement
- an OpenClaw worker for design_review and code_review

The final stage is the built-in coding.v1 closure step, so the loop produces
six executions plus an auto-generated final receipt/closure.
"""
from __future__ import annotations

import argparse
import asyncio
import json
import shutil
import sys
import time
from pathlib import Path
from typing import Any

import httpx

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from agent_net.node.runner_loop import runner_tick


SCRIPT_WORKER = r'''
import json, subprocess, sys
stage = sys.argv[1] if len(sys.argv) > 1 else "stage"
if stage == "test":
    proc = subprocess.run([
        sys.executable,
        "-m",
        "pytest",
        "tests/test_local_cli_backend.py::test_obj_local_cli_destructive_detection_ignores_option_names",
        "-q",
    ], text=True, capture_output=True, timeout=60)
    body = (proc.stdout + "\n" + proc.stderr).strip()
    status = "completed" if proc.returncode == 0 else "failed"
    artifact_type = "TestResultArtifact"
    summary = "Pytest smoke passed" if proc.returncode == 0 else "Pytest smoke failed"
else:
    body = f"# {stage}\nGenerated by deterministic script worker for AgentNexus L0-ready smoke."
    status = "completed"
    artifact_type = "RequirementSpec" if stage == "clarify" else "DesignArtifact"
    summary = f"{stage} artifact generated by script worker"
print(json.dumps({
    "contract": "agentnexus_json_v1",
    "summary": summary,
    "status": status,
    "artifact_type": artifact_type,
    "artifact_body": body,
    "evidence_refs": []
}))
'''.strip()


def _read_token(path: str) -> str:
    token_path = Path(path)
    if token_path.exists():
        return token_path.read_text(encoding="utf-8").strip()
    alt = Path.home() / ".agentnexus" / "daemon_token.txt"
    if alt.exists():
        return alt.read_text(encoding="utf-8").strip()
    raise FileNotFoundError(
        f"Daemon token not found at {token_path} or {alt}. Start the daemon first."
    )


def _resolve_command(command: str) -> str:
    if any(sep in command for sep in ("/", "\\")):
        return command
    resolved = shutil.which(command)
    if resolved:
        return resolved
    return command


def _json(data: Any) -> str:
    return json.dumps(data, ensure_ascii=False, indent=2)


async def _run(args: argparse.Namespace) -> dict[str, Any]:
    base_url = args.base_url.rstrip("/")
    token = _read_token(args.token_file)
    headers = {"Authorization": f"Bearer {token}"}
    claude_command = _resolve_command(args.claude_command)
    openclaw_command = _resolve_command(args.openclaw_command)

    async with httpx.AsyncClient(timeout=args.http_timeout_sec) as client:
        async def request(method: str, path: str, **kwargs):
            resp = await client.request(
                method,
                f"{base_url}{path}",
                headers=headers,
                **kwargs,
            )
            if resp.status_code >= 400:
                raise RuntimeError(f"{method} {path} -> {resp.status_code}: {resp.text}")
            return resp.json()

        async def post(path: str, body: dict):
            return await request("POST", path, json=body)

        async def get(path: str, params: dict | None = None):
            return await request("GET", path, params=params or {})

        async def patch(path: str, body: dict):
            return await request("PATCH", path, json=body)

        owner = (await post(
            "/owner/register",
            {"name": f"L0ReadyDemoOwner_{int(time.time())}"},
        ))["did"]

        async def register_worker(name: str, capabilities: list[str]) -> str:
            worker = await post(
                "/agents/register",
                {
                    "name": name,
                    "capabilities": capabilities,
                    "worker_type": "interactive_cli",
                },
            )
            did = worker["did"]
            await post("/owner/bind", {"owner_did": owner, "agent_did": did})
            return did

        script_did = await register_worker(
            "L0ReadyScriptPytestWorker",
            ["Clarify", "Design", "Test"],
        )
        claude_did = await register_worker(
            "L0ReadyClaudeWorker",
            ["Code", "Implement"],
        )
        openclaw_did = await register_worker(
            "L0ReadyOpenClawWorker",
            ["Review", "QA"],
        )

        intake = await post(
            "/coordination/coding/intake",
            {
                "owner_did": owner,
                "actor_did": owner,
                "objective": (
                    "L0-ready smoke: produce a tiny change plan, implementation "
                    "summary, reviews, and pytest evidence using script, Claude, "
                    "and OpenClaw workers."
                ),
                "complexity": "low",
                "risk_level": "normal",
                "cost_policy": "low",
            },
        )
        session = intake["session"]
        sid = session["coordination_session_id"]
        run_id = session["playbook_run_id"]
        enclave_id = session["enclave_id"]

        config = {
            "daemon_url": base_url,
            "owner_did": owner,
            "secretary_agent": owner,
            "defaults": {
                "workdir": ".",
                "timeout_sec": args.worker_timeout_sec,
                "max_retries_per_stage": 2,
                "max_total_executions": 20,
                "max_wall_clock_sec": 1800,
                "max_output_bytes": 80000,
                "network_access": "local_only",
                "allowed_commands": [
                    "python",
                    "claude",
                    "claude.cmd",
                    "openclaw",
                    "openclaw.cmd",
                    sys.executable,
                    claude_command,
                    openclaw_command,
                ],
            },
            "workers": {
                "script_pytest": {
                    "worker_did": script_did,
                    "agent_name": "L0ReadyScriptPytestWorker",
                    "worker_type": "interactive_cli",
                    "adapter": "local_cli",
                    "command": sys.executable,
                    "args": ["-c", SCRIPT_WORKER, "{stage}"],
                    "roles": ["clarifier", "designer", "tester"],
                    "capabilities": ["Clarify", "Design", "Test"],
                    "output_contract": "agentnexus_json_v1",
                    "output_adapter": "agentnexus_json_v1",
                },
                "claude_implementer": {
                    "worker_did": claude_did,
                    "agent_name": "L0ReadyClaudeWorker",
                    "worker_type": "interactive_cli",
                    "adapter": "local_cli",
                    "command": claude_command,
                    "args": [
                        "-p",
                        (
                            "Return a concise implementation summary for "
                            "AgentNexus smoke stage implement. No tools. {prompt}"
                        ),
                        "--output-format",
                        "text",
                        "--max-turns",
                        "1",
                    ],
                    "roles": ["developer"],
                    "capabilities": ["Code", "Implement"],
                    "output_contract": "agentnexus_json_v1",
                    "output_adapter": "text_artifact",
                    "artifact_type": "ImplementationArtifact",
                },
                "openclaw_reviewer": {
                    "worker_did": openclaw_did,
                    "agent_name": "L0ReadyOpenClawWorker",
                    "worker_type": "interactive_cli",
                    "adapter": "local_cli",
                    "command": openclaw_command,
                    "args": [
                        "agent",
                        "--local",
                        "--json",
                        "--session-key",
                        "agent:agentnexus:{stage}-{run_id}",
                        "--message",
                        "Review briefly and say approved if acceptable. {prompt}",
                    ],
                    "roles": ["reviewer"],
                    "capabilities": ["Review", "QA"],
                    "output_contract": "agentnexus_json_v1",
                    "output_adapter": "openclaw_json",
                    "artifact_type": "OpenClawReviewArtifact",
                },
            },
        }

        async def list_sessions(**kwargs):
            data = await get(
                "/coordination/sessions",
                {k: v for k, v in kwargs.items() if v},
            )
            return data.get("sessions", [])

        async def next_action(session_id: str, actor: str):
            data = await get(
                f"/coordination/sessions/{session_id}/next-action",
                {"actor_did": actor},
            )
            return data.get("action", {})

        async def session_detail(session_id: str, actor: str):
            data = await get(
                f"/coordination/sessions/{session_id}",
                {"actor_did": actor},
            )
            detail = data.get("session", data)
            detail["artifacts"] = (
                await get(
                    f"/coordination/sessions/{session_id}/artifacts",
                    {"actor_did": actor},
                )
            ).get("artifacts", [])
            detail["receipts"] = (
                await get(
                    f"/coordination/sessions/{session_id}/receipts",
                    {"actor_did": actor},
                )
            ).get("receipts", [])
            return detail

        async def create_execution(**body):
            return await post("/coordination/executions", body)

        async def submit_result(execution_id: str, body: dict):
            return await post(f"/coordination/executions/{execution_id}/result", body)

        async def advance(session_id: str, rid: str, actor: str):
            return await post(
                f"/coordination/coding/{session_id}/runs/{rid}/advance",
                {"actor_did": actor},
            )

        async def create_decision(**kwargs):
            from agent_net.node.secretary_gateway import handle_decision_gate

            return await handle_decision_gate(**kwargs)

        async def update_execution(execution_id: str, body: dict):
            return await patch(f"/coordination/executions/{execution_id}", body)

        history: list[dict[str, Any]] = []
        for tick in range(1, args.max_ticks + 1):
            actions = await runner_tick(
                config=config,
                list_sessions=list_sessions,
                get_next_action=next_action,
                get_session_detail=session_detail,
                create_execution=create_execution,
                submit_result=submit_result,
                call_advance=advance,
                create_decision=create_decision,
                update_execution=update_execution,
                actor_did=owner,
                owner_did=owner,
            )
            history.extend({"tick": tick, **action} for action in actions)
            if args.verbose:
                print(_json({"tick": tick, "actions": actions}))

            current_session = await get(
                f"/coordination/sessions/{sid}",
                {"actor_did": owner},
            )
            status = current_session.get("session", current_session).get("status")
            if status in ("completed", "closed", "failed", "aborted"):
                break
            await asyncio.sleep(args.tick_sleep_sec)

        detail = await get(f"/coordination/sessions/{sid}", {"actor_did": owner})
        artifacts = await get(
            f"/coordination/sessions/{sid}/artifacts",
            {"actor_did": owner},
        )
        receipts = await get(
            f"/coordination/sessions/{sid}/receipts",
            {"actor_did": owner},
        )
        executions = await get(
            f"/coordination/sessions/{sid}/executions",
            {"actor_did": owner},
        )
        timeline = await get(
            f"/coordination/sessions/{sid}/timeline",
            {"actor_did": owner},
        )
        session_body = detail.get("session", detail)

        return {
            "owner_did": owner,
            "workers": {
                "script_pytest": script_did,
                "claude": claude_did,
                "openclaw": openclaw_did,
            },
            "coordination_session_id": sid,
            "run_id": run_id,
            "enclave_id": enclave_id,
            "session_status": session_body.get("status"),
            "artifact_count": artifacts.get("count", len(artifacts.get("artifacts", []))),
            "receipt_count": receipts.get("count", len(receipts.get("receipts", []))),
            "execution_count": executions.get("count", len(executions.get("executions", []))),
            "timeline_count": len(timeline.get("timeline", [])),
            "dashboard_url": (
                f"{base_url}/ui/enclaves?enclave_id={enclave_id}"
                f"&run_id={run_id}&actor_did={owner}"
            ),
            "stage_history": history,
            "notes": [
                "coding.v1 final stage is auto-closed by the advance API",
                "expected shape: 6 executions, 6 artifacts, 7 receipts, completed session",
            ],
        }


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Run the AgentNexus L0-ready real-worker Objective Loop demo."
    )
    parser.add_argument("--base-url", default="http://127.0.0.1:8765")
    parser.add_argument("--token-file", default="data/daemon_token.txt")
    parser.add_argument("--claude-command", default="claude")
    parser.add_argument("--openclaw-command", default="openclaw")
    parser.add_argument("--worker-timeout-sec", type=int, default=120)
    parser.add_argument("--http-timeout-sec", type=int, default=45)
    parser.add_argument("--max-ticks", type=int, default=24)
    parser.add_argument("--tick-sleep-sec", type=float, default=0.2)
    parser.add_argument("--verbose", action="store_true")
    return parser


def main() -> None:
    args = _parser().parse_args()
    summary = asyncio.run(_run(args))
    print(_json(summary))


if __name__ == "__main__":
    main()
